"""Control-store protocol — shared interface for local SQLite and remote HTTP backends."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from tokenops.control.models import (
    BudgetSpec,
    PolicyInstance,
    RunRecord,
    RunRegistration,
    Segment,
)


@runtime_checkable
class ControlStore(Protocol):
    """Persistence + ledger surface consumed by agents, UIs, and the Governor."""

    def close(self) -> None: ...

    # segments
    def upsert_segment(self, seg: Segment) -> Segment: ...
    def get_segment(self, sid: str) -> Segment | None: ...
    def list_segments(self) -> list[Segment]: ...
    def delete_segment(self, sid: str) -> None: ...

    # budgets
    def upsert_budget(self, b: BudgetSpec) -> BudgetSpec: ...
    def get_budget(self, bid: str) -> BudgetSpec | None: ...
    def list_budgets(self) -> list[BudgetSpec]: ...
    def delete_budget(self, bid: str) -> None: ...

    # policy instances
    def upsert_policy_instance(self, pi: PolicyInstance) -> PolicyInstance: ...
    def get_policy_instance(self, pid: str) -> PolicyInstance | None: ...
    def list_policy_instances(self) -> list[PolicyInstance]: ...
    def delete_policy_instance(self, pid: str) -> None: ...
    def seed_default_governance_if_empty(self, governance: dict | None = None) -> bool: ...
    def clear_all(self) -> None: ...
    def clear_governance(self) -> None: ...
    def reseed_governance(self, governance: dict | None = None) -> bool: ...

    # registration
    def register_run(self, reg: RunRegistration) -> RunRegistration: ...
    def resolve_run(self, run_id: str) -> RunRegistration: ...
    def get_run_registration(self, run_id: str) -> RunRegistration | None: ...

    # governor bridge
    def governance_config_for(self, agent: str) -> dict: ...

    # run history
    def create_run(self, rec: RunRecord) -> RunRecord: ...
    def update_run(self, run_id: str, **fields: Any) -> None: ...
    def get_run(self, run_id: str) -> RunRecord | None: ...
    def list_runs(self, *, problematic_only: bool = False, limit: int = 200) -> list[RunRecord]: ...
    def run_tag_keys(self, *, limit: int = 500) -> list[str]: ...

    # shared ledger
    def ledger_add_spent(self, budget_id: str, segment_key: str, period: str, delta: int) -> int: ...
    def ledger_get_spent(self, budget_id: str, segment_key: str, period: str) -> int: ...
    def ledger_admit(self, segment_key: str) -> int: ...
    def ledger_complete(self, segment_key: str) -> int: ...
    def ledger_inflight(self, segment_key: str) -> int: ...
    def ledger_mark_halted(self, run_id: str, reason: str = "") -> None: ...
    def ledger_is_halted(self, run_id: str) -> bool: ...
    def ledger_halt_reason(self, run_id: str) -> str | None: ...
    def ledger_clear_halt(self, run_id: str) -> None: ...
